### ISSUE TITLE
Several Issues about execution

### ISSUE THREAD

**Issue by RPFey** [ubc-vision/nf-soft-mining#1]
Hi, thank you for sharing the code ! There are still several mistakes in the current version. 

1. I cannot find `LLFF_NDC_SCENES` in examples.utils , which is imported in `examples/utils.py`.

2. I cannot find `nerfacc.losses`, which is imported in `examples/losses.py`.

3. When running the LMC sampling method,  I get the error when setting the `proposal_requires_grad` variable to `True`

```
RuntimeError: Trying to backward through the graph a second time (or directly access saved tensors after they have already been freed). Saved intermediate values of the graph are freed when you call .backward() or autograd.grad(). Specify retain_graph=True if you need to backward through the graph a second time or if you need to access saved tensors after calling backward.
```

Thank you in advance if you could fix these bugs !

**Comment by shakibakh** [comment]
@RPFey  Thank you for the comment. A few local changes haven't been pushed before. The current main branch should be ok. I will close the issue. Feel free to reopen it if there is any problem.

**Comment by shakibakh** [comment]
@RPFey Thank you for the comment. A few local changes haven't been pushed before. The current main branch should be ok. I will close the issue. Feel free to reopen it if there is any problem.
