### ISSUE TITLE
I cannot the implementation of "sampling type:lmc"

### ISSUE THREAD

**Issue by weixiang-zhang** [ubc-vision/nf-soft-mining#4]
Thanks for your contribution.
I want to see how LMC implement in this repo. But I can only find that sampling type = 'uniform' or 'lindisp' ('sampling' function in estimators/prop_net.py)
And I cannot find "lmc" globally in this codebase. So How can I find the implementation?
Thanks!

**Comment by weixiang-zhang** [comment]
different sampling meanings. lmc.py is in datasets folder.

**Comment by shakibakh** [comment]
@zwxdxcm As you mentioned, the implementation is in lmc.py.
